# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x66rame.proto\x12\x1a\x61utosplit.network.protobuf"H\n\x05\x46rame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0c\n\x04mode\x18\x04 \x01(\tb\x06proto3'
)


_FRAME = DESCRIPTOR.message_types_by_name["Frame"]
Frame = _reflection.GeneratedProtocolMessageType(
    "Frame",
    (_message.Message,),
    {
        "DESCRIPTOR": _FRAME,
        "__module__": "frame_pb2"
        # @@protoc_insertion_point(class_scope:autosplit.network.protobuf.Frame)
    },
)
_sym_db.RegisterMessage(Frame)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _FRAME._serialized_start = 43
    _FRAME._serialized_end = 115
# @@protoc_insertion_point(module_scope)
