"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Frame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IMAGE_DATA_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes = ...
    width: builtins.int = ...
    height: builtins.int = ...
    mode: typing.Text = ...
    def __init__(
        self,
        *,
        image_data: builtins.bytes = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        mode: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "height",
            b"height",
            "image_data",
            b"image_data",
            "mode",
            b"mode",
            "width",
            b"width",
        ],
    ) -> None: ...

global___Frame = Frame
