# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pineapple_frame.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pineapple_frame.proto',
  package='autosplit.network.protobuf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15pineapple_frame.proto\x12\x1a\x61utosplit.network.protobuf\"\x1c\n\x0ePineappleFrame\x12\n\n\x02id\x18\x01 \x01(\x05\x62\x06proto3'
)




_PINEAPPLEFRAME = _descriptor.Descriptor(
  name='PineappleFrame',
  full_name='autosplit.network.protobuf.PineappleFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='autosplit.network.protobuf.PineappleFrame.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['PineappleFrame'] = _PINEAPPLEFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PineappleFrame = _reflection.GeneratedProtocolMessageType('PineappleFrame', (_message.Message,), {
  'DESCRIPTOR' : _PINEAPPLEFRAME,
  '__module__' : 'pineapple_frame_pb2'
  # @@protoc_insertion_point(class_scope:autosplit.network.protobuf.PineappleFrame)
  })
_sym_db.RegisterMessage(PineappleFrame)


# @@protoc_insertion_point(module_scope)
