name: Lint

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name: Lint
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip
    - name: Run Linter
      run: |
        make
