name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        poetry install
    - name: Run Linter
      run: |
        make lint