name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install ".[dev]"
    - name: lint
      run: |
        make lint
