name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install -r requirements/dev.txt
        sudo apt install protobuf-compiler
        make compile env=linux
    - name: Run unit tests
      run: |
        make test env=linux